version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '04:00'
      timezone: America/Toronto
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
      - github-actions
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
      time: '04:00'
      timezone: America/Toronto
    versioning-strategy: increase
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
      - ruby
