# site settings
title: Devon Powell
description: ""
author:
  name: Devon Powell
  email: devon.f.powell@gmail.com
header_pages:
  - _pages/about.md
show_excerpts: true

# build settings
remote_theme: jekyll/minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme
include:
  - _pages
exclude:
  - README.md
defaults:
  - scope:
      path: _pages
      type: pages
      layout: page
    values:
      permalink: /:basename

# minima settings
minima:
  skin: dark
  social_links:
    twitter: devpow112
    github: devpow112
    linkedin: devpow112
