# site settings
title: Devon Powell
description: >-
  Welcome to my site! I am a full-time senior software developer currently
  working in the educational technologies sector. I hope you find this random
  collection of coding stuff as interesting as I do.
author:
  name: Devon Powell
  email: devon.f.powell@gmail.com
repository: devpow112/devpow112.github.io
header_pages:
  - _pages/about.md
show_excerpts: true

# build settings
remote_theme: jekyll/minima
strict_front_matter: true
plugins:
  - jekyll-feed
  - jekyll-remote-theme
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
collections:
  assets:
    permalink: /:path
    output: true
defaults:
  - scope:
      path: _pages
      type: pages
    values:
      layout: page
      permalink: /:basename
  - scope:
      path: _posts
      type: posts
    values:
      layout: post

# minima settings
minima:
  skin: dark
  social_links:
    - platform: github
      user_url: https://github.com/devpow112
    - platform: linkedin
      user_url: https://linkedin.com/in/devpow112
    - platform: facebook
      user_url: https://facebook.com/devpow112
    - platform: twitter
      user_url: https://twitter.com/devpow112
    - platform: stackoverflow
      user_url: https://stackoverflow.com/users/15813146
    - platform: youtube
      user_url: https://youtube.com/devpow112

# sass converter
sass:
  style: compressed
