# site settings
title: Devon Powell
description: >-
  Welcome to my site! I am a full-time senior software developer currently
  working in the educational technologies sector. I've been in the tech
  industry, in one form or the other, for over 14 years now.
author:
  name: Devon Powell
  email: devon.f.powell@gmail.com
header_pages:
  - _pages/about.md
show_excerpts: true

# build settings
remote_theme: jekyll/minima
strict_front_matter: true
plugins:
  - jekyll-feed
  - jekyll-remote-theme
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vendor
defaults:
  - scope:
      path: _pages
      type: pages
    values:
      layout: page
      permalink: /:basename
  - scope:
      path: _posts
      type: posts
    values:
      layout: post

# minima settings
minima:
  skin: dark
  social_links:
    github: devpow112
    linkedin: devpow112
