name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up ruby
        uses: ruby/setup-ruby@v1.70.1
        with:
          bundler-cache: true
      - name: Run build
        run: bundle exec jekyll build
