name: CI
on:
  workflow_call
permissions:
  contents: read
jobs:
  check-formatting-markdown:
    name: Check Formatting (Markdown)
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check formatting
        uses: davidanson/markdownlint-cli2-action@v14.0.0
        with:
          globs: '**/*.md'
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.165.0
        with:
          bundler-cache: true
      - name: Set up Pages
        uses: actions/configure-pages@v4.0.0
        id: pages
      - name: Build
        run: >
          bundle exec jekyll build
          --baseurl '${{steps.pages.outputs.base_path}}'
        env:
          JEKYLL_ENV: production
          JEKYLL_GITHUB_TOKEN: ${{github.token}}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.0
        if: github.event_name != 'pull_request'
