name: Release
on:
  push:
    branches:
      - main
permissions:
  contents: read
concurrency: release
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
  cd:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1.0.0
