
name: Release
on:
  push:
    branches: main
concurrency: release
permissions:
  contents: read
jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml
  cd:
    name: CD
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2.0.5
        id: deployment
